Phantomsmedia/Wavelength

Ph.VR/DAC/DAC_Config_Units.sqf

Added Insurgent Faction (RHS) as case 8 for DAC.

Added Insurgent DAC Faction (RHS)

---

Ph.VR/DAC/DAC_Config_Units.sqf

Updated Faction to Fix small problem in DAC case 8

Updated Faction to Fix small problem DAC case 8

---

Ph.VR/f/radios/acre2/acre2_settings.sqf

Updated Radio List

---

Custom Factions/CTRG/f_assignGear_nato.sqf
Custom Factions/Contractors/Desert/f_assignGear_aaf.sqf
Custom Factions/FIA/f_assignGear_nato.sqf
Custom Factions/PMC/f_assignGear_aaf.sqf
Custom Factions/Rebels/Desert/f_assignGear_aaf.sqf
Custom Factions/Rebels/Woodland/f_assignGear_aaf.sqf
Custom Factions/Russian Army/EMR Summer/f_assignGear_csat.sqf
Custom Factions/Russian Army/Flora/f_assignGear_csat.sqf
Custom Factions/Russian Army/Mountain Les/f_assignGear_csat.sqf
Custom Factions/US Army/OCP/f_assignGear_nato.sqf
Custom Factions/US Army/UCP/f_assignGear_nato.sqf
Custom Factions/US Marine Corps/Desert/f_assignGear_nato.sqf
Custom Factions/US Marine Corps/Woodland/f_assignGear_nato.sqf
Ph.VR/f/assignGear/f_assignGear_aaf.sqf
Ph.VR/f/assignGear/f_assignGear_csat.sqf
Ph.VR/f/assignGear/f_assignGear_nato.sqf
Ph.VR/f/briefing/f_briefing_aaf.sqf
Ph.VR/f/briefing/f_briefing_civ.sqf
Ph.VR/f/briefing/f_briefing_csat.sqf
Ph.VR/f/briefing/f_briefing_nato.sqf
Ph.VR/f/groupMarkers/f_setLocalGroupMarkers.sqf
Ph.VR/f/radios/acre2/acre2_settings.sqf
Ph.VR/f/radios/tfr/fn_tfr_addRadios.sqf
Ph.VR/f/radios/tfr/tfr_settings.sqf
Ph.VR/mission.sqm
README.md

Main build is clean, we'll hold backup build there.

Merge to Stay with Main Build

---

Ph.VR/f/spect/config.hpp
Ph.VR/f/spect/fn_CamInit.sqf
Ph.VR/f/spect/fn_HandleMenu.sqf

Added dank cinematic camera

---

Ph.VR/description.ext
Ph.VR/f/config.hpp

Should help clean up the description.ext.
The BWMF stuff won't work for a bit until the stuff is updated with the new assignGear scripts.

Moved F3 CfgFunction definitions into f/config.hpp and added the BWMF code for CfgLoadouts,

---

Ph.VR/DAC/DAC_Config_Units.sqf

Added LOP units for the future. Changed formatting for easy editing and understanding of each faction.
Factions came from authors credited in the comments and myself.

Added factions for the future and changed formatting,

---

Ph.VR/DAC/DAC_Config_Units.sqf

Fixed line 5 comment

---

Ph.VR/DAC/DAC_Config_Creator.sqf
Ph.VR/Loadouts/bluefor_standard.hpp
Ph.VR/Loadouts/indfor_standard.hpp
Ph.VR/Loadouts/opfor_standard.hpp
Ph.VR/f/assignGear/fn_assignGearMan.sqf
Ph.VR/f/radios/acre2/acre2_settings.sqf

~~No loadout found for (typeOf O_helicrew_F)~~
~~No loadout found for (typeOf O_Pilot_F)~~
~~No loadout found for (typeOf O_support_AMG_F)~~
~~No loadout found for (typeOf O_diver_TL_F)~~
~~No loadout found for (typeOf O_diver_F)~~
~~No loadout found for (typeOf B_Pilot_F)~~
~~No loadout found for (typeOf B_support_AMG_F)~~
~~No loadout found for (typeOf B_diver_TL_F)~~
~~No loadout found for (typeOf B_diver_F)~~
~~No loadout found for (typeOf I_pilot_F)~~
~~No loadout found for (typeOf I_helicrew_F)~~
~~No loadout found for (typeOf I_support_AMG_F)~~
~~No loadout found for (typeOf I_diver_F)~~

Standard loadouts missing some unit classes.

---

Ph.VR/DAC/DAC_Config_Units.sqf

Changed formatting of DAC_Config_Units.sqf to make it easier to understand.

Changed formatting of DAC_units.sqf

---

Ph.VR/DAC/DAC_Config_Units.sqf

Further Changed formatting of DAC_Config_Units

Further Changed formatting of DAC_Config_Units

---

WL.VR/f/spect/fn_HandleMenu.sqf

Changed cinematic camera to use the spect camera position when initializing

---

WL.VR/Loadouts/bluefor_standard.hpp
WL.VR/Loadouts/indfor_standard.hpp
WL.VR/Loadouts/opfor_standard.hpp

Some things to take note of:
-SDAR has gotten gud, is now viable above water. Carbine may be unnecessary but is included for now.
-Uniform vest and helmet additions to backpack were commented out for want of backpack space
-Custom factions need to be done later, only the NATO/CSAT/AAF bases have been altered.

Updated diver gear for base loadouts

---

WL.VR/mission.sqm

Added DAC examples for reference or to be used as a base to be modified for own use.

Added DAC Examples

---

Custom Factions/BLUFOR/CDF/bluefor_standard.hpp
Custom Factions/BLUFOR/CTRG/bluefor_standard.hpp
Custom Factions/BLUFOR/FIA/bluefor_standard.hpp
Custom Factions/BLUFOR/NATO/bluefor_standard.hpp
Custom Factions/BLUFOR/USA (Army 2014)/OCP/bluefor_standard.hpp
Custom Factions/BLUFOR/USA (Army 2014)/UCP/bluefor_standard.hpp
Custom Factions/BLUFOR/USA (USMC 2014)/Desert/bluefor_standard.hpp
Custom Factions/BLUFOR/USA (USMC 2014)/Woodland/bluefor_standard.hpp
Custom Factions/INDEPENDENT/AAF/indfor_standard.hpp
Custom Factions/INDEPENDENT/Afghan Militia/indfor_standard.hpp
Custom Factions/INDEPENDENT/African Militia/indfor_standard.hpp
Custom Factions/INDEPENDENT/Contractors/Desert/indfor_standard.hpp
Custom Factions/INDEPENDENT/Insurgents/indfor_standard.hpp
Custom Factions/INDEPENDENT/People's Liberation Army (Modern)/indfor_standard.hpp
Custom Factions/OPFOR/CSAT/opfor_standard.hpp
Custom Factions/OPFOR/Russia (VDV)/EMR/opfor_standard.hpp
Custom Factions/OPFOR/Russia (VDV)/Flora/opfor_standard.hpp
Custom Factions/OPFOR/Russia (VDV)/Mountain Flora/opfor_standard.hpp
Custom Factions/OPFOR/SLA/opfor_standard.hpp
Custom Factions/_Incomplete/Ukrainian Army/bluefor_standard.hpp

Needs testing for hpp crashes but besides that all should be good.

Added new diver gear to all custom factions.

---

WL.VR/f/headlessclient/passToHCs.sqf
WL.VR/init.sqf

Update passToHCs script to detect DAC loading and support transferring trigger waypoints.

Update passToHCs script to detect DAC and trigger waypoints.

---

WL.VR/f/headlessclient/passToHCs.sqf

Will need some testing but this should support using the customized DAC that supports HC.

Added logic to only transfer AI that are not already on an HC. (This should support DAC)

---

WL.VR/f/pabstMarkers/fn_playerInit.sqf

Added support for displaying pabst markers on Tao Folding Map.

---

WL.VR/f/assignGear/fn_assignGearMan.sqf

This is @Zriel88's PR #278 with the parts that we want cherry picked, we don't want to modify the default loadout files because that'll end up with us having goggles in instances where we don't expect it, better to require the misdev to add the line for now and we won't have to modify every single loadout file for the custom factions.

Added the ability to assign googles and randomize the selection. (Cherry Picked)

---

Custom Factions/BLUFOR/CTRG/bluefor_standard.hpp
Custom Factions/BLUFOR/NATO/bluefor_standard.hpp
Custom Factions/_Incomplete/Ukrainian Army/bluefor_standard.hpp
WL.VR/Loadouts/bluefor_standard.hpp

Fix Issue #299 (HE GL Type Fix)

Fix Issue 299 (HE GL Type Fix)

---

WL.VR/f/assignGear/fn_assignGearMan.sqf
WL.VR/f/assignGear/fn_assignGearVehicle.sqf

Rewrote assignGear script to use callback model to allow for misdev to specify own configFile path. (For #290)

Rewrote assignGear script to use callback model.

---

WL.VR/DAC/DAC_Config_Units.sqf

Fixed DAC Unit Config Order for Crewman/Pilot/Group Leader.

---

WL.VR/Loadouts/bluefor_standard.hpp
WL.VR/f/assignGear/fn_assignGearVehicle.sqf

Add ability to add backpacks into cargo of vehicles using loadouts. (IE Parachutes)

TransportBackpacks

---

WL.VR/f/radios/acre2/acre2_briefingInit.sqf

Added privates to acre2_briefingInit and added try/catch to ensure script still works even if there is a failure on one or more channels.

acre2_briefingInit fixes and error handling changes

---

Custom Factions/BLUFOR/CDF/bluefor_standard.hpp
Custom Factions/BLUFOR/CTRG/bluefor_standard.hpp
Custom Factions/BLUFOR/FIA/bluefor_standard.hpp
Custom Factions/BLUFOR/NATO/bluefor_standard.hpp
Custom Factions/BLUFOR/USA (Army 2014)/OCP/bluefor_standard.hpp
Custom Factions/BLUFOR/USA (Army 2014)/UCP/bluefor_standard.hpp
Custom Factions/BLUFOR/USA (USMC 2014)/Desert/bluefor_standard.hpp
Custom Factions/BLUFOR/USA (USMC 2014)/Woodland/bluefor_standard.hpp
Custom Factions/INDEPENDENT/AAF/indfor_standard.hpp
Custom Factions/INDEPENDENT/Afghan Militia/indfor_standard.hpp
Custom Factions/INDEPENDENT/African Militia/indfor_standard.hpp
Custom Factions/INDEPENDENT/Contractors/Desert/indfor_standard.hpp
Custom Factions/INDEPENDENT/Insurgents/indfor_standard.hpp
Custom Factions/INDEPENDENT/People's Liberation Army (Modern)/indfor_standard.hpp
Custom Factions/OPFOR/CSAT/opfor_standard.hpp
Custom Factions/OPFOR/Russia (VDV)/EMR/opfor_standard.hpp
Custom Factions/OPFOR/Russia (VDV)/Flora/opfor_standard.hpp
Custom Factions/OPFOR/Russia (VDV)/Mountain Flora/opfor_standard.hpp
Custom Factions/OPFOR/SLA/opfor_standard.hpp
Custom Factions/_Incomplete/Ukrainian Army/bluefor_standard.hpp
WL.VR/CfgLoadouts.hpp
WL.VR/Loadouts/bluefor_standard.hpp
WL.VR/Loadouts/indfor_standard.hpp
WL.VR/Loadouts/opfor_standard.hpp
WL.VR/Loadouts/russian_standard.hpp
WL.VR/description.ext
WL.VR/f/assignGear/fn_assignGearMan.sqf

Added support for changing between Basic & Advanced ACE Medical.

Added support for changing between Basic & Advanced ACE Medical.

---

WL.VR/f/assignGear/fn_assignGearMan.sqf

I have made so you can put some different weapons in the loadout (or launchers or handguns) each one with their different type of ammunition, and it will only give you the magazines you have specified that are compatible with that weapon (even the ammo for a grenade launcher if there different avaliable).It will also give you every grenade or explosive specified, as it is supposed you have to get everything from those.
IE
handguns[] = {"RH_fn57" ,"RH_g17"}; /// randomized FN 57 and Glock 17
magazines[] = {"RH_20Rnd_57x28_FN:3","RH_17Rnd_9x19_g17:3",WEST_SMOKE_WHITE}; //Magazines for each handgun (each one is only compatible with the corresponding weapon.
You will receive one of those handguns, and 3 magazines of the needed ammo, plus the smokeshell.

Random weapons improvement

---

WL.VR/Loadouts/indfor_standard.hpp

Removed RHS RPG

---

WL.VR/CfgLoadouts.hpp
WL.VR/f/ace/ace_medical_settings.hpp

-Removed QuikClot, not specialized in any category therefore not useful.
-Doubled number of tourniquets for GI.
-Added personal aid kit to medic.

Adjusted AMS Settings

---

WL.VR/mission.sqm

Adds 2 scouts to each platoon element. They are spotters and so use the spotter class for each faction.

Add scouts to each platoon element

---

WL.VR/CfgEventHandlers.hpp
WL.VR/CfgLoadouts.hpp

Fixes for Issues #353 and #351

---

WL.VR/CfgLoadouts.hpp

Decreased Medics amount of "ACE_atropine" from 12 to 6 in CfgLoadouts.hpp

Decreased Medics amount of "ACE_atropine"

---

WL.VR/f/assignGear/fn_assignGearMan.sqf
WL.VR/f/spect/fn_DrawTags.sqf

Added weight debugging system

---

WL.VR/f/briefing/fn_showOrbatNotes.sqf
WL.VR/f/pabstMarkers/defines_unitsAndGroups.hpp
WL.VR/f/pabstMarkers/fn_getGroupMarkerStyle.sqf

ORBAT was overhauled. More entries were added to unitsAndGroups.hpp. Code has been tested for basic functionality, but still needs full stress testing.
Feature request #380.
New look: https://i.gyazo.com/22c83a654c7c9e0c33100a218dea1a10.png

ORBAT Overhaul

---

WL.VR/f/spect/fn_DrawTags.sqf

It was really quite broken for some reason.

Fixed fn_DrawTags.sqf
